# This sets up a certificate for the ingress subdomain
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-certificate
spec:
  secretName: {{ .Release.Name }}-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: {{ .Values.subdomain | quote }}
  dnsNames:
  - {{ .Values.subdomain | quote }}
