{{- if eq .Values.ssh.enable true }}
# Store ssh public key in a configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ssh-pubkey
data:
  authorized_keys: |
    {{ .Values.ssh.pubkey }}
{{- end }}
