{{- if eq .Values.s3.enable true }}
# S3 secrets stored in ~/.config/rclone/rclone.conf and ~/.aws/credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3-key
type: Opaque
stringData:
  s3_endpoint: {{ .Values.s3.endpoint | quote }}
  s3_access_key: {{ .Values.s3.access_key | quote }}
  s3_secret_key: {{ .Values.s3.secret_key | quote }}
{{- end }}
